import { Food } from "./app/shared/models/Food";

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Pizza',
    price: 123,
    cookingTime: '40-50',
    favourite: false,
    origins: ['Italy'],
    stars: 4.0,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Burger',
    price: 12,
    cookingTime: '40-50',
    favourite: true,
    origins: ['Italy', 'Germany'],
    stars: 5,
    imageUrl: 'assets/food-2.jpg',
    tags: ['FastFood', 'Burger'],
  },
  {
    id: '3',
    name: 'Biriyani',
    price: 15,
    cookingTime: '40-50',
    favourite: true,
    origins: ['India', 'Pakistan'],
    stars: 1,
    imageUrl: 'assets/food-3.jpg',
    tags: ['Lunch', 'Biriyani', 'Dinner'],
  },
  {
    id: '4',
    name: 'Chicken Mandhi',
    price: 30,
    cookingTime: '40-50',
    favourite: false,
    origins: ['Qatar', 'UAE'],
    stars: 3,
    imageUrl: 'assets/food-4.jpg',
    tags: [],
  },
  {
    id: '5',
    name: 'Porotta',
    price: 15,
    cookingTime: '40-50',
    favourite: true,
    origins: ['India', 'kerala'],
    stars: 2,
    imageUrl: 'assets/food-5.jpg',
    tags: ['Dinner'],
  },
  {
    id: '6',
    name: 'Icecream',
    price: 15,
    cookingTime: '40-50',
    favourite: true,
    origins: ['India'],
    stars: 5,
    imageUrl: 'assets/food-6.jpg',
    tags: [],
  },
];
